# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'Pay-As-You-Go(1)(5a5ef6cc-ba75-424c-abef-b3332a0ef8c8)'
      command: 'restore'
      projects: '**/*.csproj'
    displayName: 'Restore'

  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'Pay-As-You-Go(1)(5a5ef6cc-ba75-424c-abef-b3332a0ef8c8)'
      command: 'build'
      projects: '**/*.csproj'
      arguments: '-Norestore-'
    displayName: 'build'

  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'Pay-As-You-Go(1)(5a5ef6cc-ba75-424c-abef-b3332a0ef8c8)'
      command: 'test'
      projects: '**/*.csproj'
      arguments: '-Norestore-'
    displayName: 'test'

  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'Pay-As-You-Go(1)(5a5ef6cc-ba75-424c-abef-b3332a0ef8c8)'
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'off'
    displayName: 'package'

  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'Pay-As-You-Go(1)(5a5ef6cc-ba75-424c-abef-b3332a0ef8c8)'
      command: 'publish'
      publishWebProjects: false
      projects: '**/Web.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'
      modifyOutputPath: false
    displayName: 'publish'

